In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
iris = load_iris()

df=pd.DataFrame(data=iris.data , columns=iris.feature_names)
df['species'] = iris.target
df['species'] = df['species'].map({0:'setosa',1:'versicolor',2:'virginica'})



print(df.sample(4))

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
111                6.4               2.7                5.3               1.9   
40                 5.0               3.5                1.3               0.3   
16                 5.4               3.9                1.3               0.4   
124                6.7               3.3                5.7               2.1   

       species  
111  virginica  
40      setosa  
16      setosa  
124  virginica  


In [3]:
print(df.head(5))


   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa  


In [4]:
x = iris.data
y = iris.target

In [5]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

In [6]:
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [7]:
model = RandomForestClassifier(random_state=42)
model.fit(xtrain,ytrain)

RandomForestClassifier(random_state=42)

In [8]:
ypred=model.predict(xtest)

In [9]:
print('confusion matrix: ')
print(confusion_matrix(ytest,ypred))
print('classification report: ')
print(classification_report(ytest,ypred))

confusion matrix: 
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
classification report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [15]:
new_measurements = [[1.4, 2.9, 5.6, 4.0]]
new_measurements_scaled = scaler.transform(new_measurements)
prediction = model.predict(new_measurements_scaled)
predicted_species = iris.target_names[prediction[0]]
print(f"The predicted species is: {predicted_species}")

The predicted species is: virginica


In [11]:
from sklearn.svm import SVC

In [16]:
svm_model = SVC(kernel='rbf', C=1.0, gamma='auto')
svm_model.fit(xtrain, ytrain)
y_pred = svm_model.predict(xtest)

In [17]:
print("Confusion Matrix:")
print(confusion_matrix(ytest, ypred))

print("\nClassification Report:")
print(classification_report(ytest, ypred))

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [19]:
new_measurements = [[1.4, 2.9, 5.6, 4.0]]
new_measurements_scaled = scaler.transform(new_measurements)
prediction = svm_model.predict(new_measurements_scaled)
predicted_species = iris.target_names[prediction[0]]
print(f"The predicted species is: {predicted_species}")

The predicted species is: virginica
